language: python
sudo: required
services:
  - docker
matrix:
  fast_finish: true
env:
  - ARCH=x86 BASE_IMAGE_PREFIX=""
  - ARCH=arm BASE_IMAGE_PREFIX="arm32v7/"
before_install:
#  - python --version
# command to install dependencies
install:
  #- cd ${TRAVIS_BUILD_DIR}/build
  # - ./ambianic-build.sh
  - pip3 install -U codecov
# command to run tests
script:
  # Raspberry PI section
  # prepare qemu
  - TAG=dev-${ARCH}
  # verbose output mode
  - set -x
  # fail fast
  - set -e
  - cd ${TRAVIS_BUILD_DIR}/build
  - >
      if [ "$ARCH" == "arm" ]; then
        docker run --rm --privileged multiarch/qemu-user-static:register --reset
      fi
  # build image
  - sudo docker build -f Dev.Dockerfile -t ambianic/ambianic:$TAG --build-arg BASE_IMAGE=$BASE_IMAGE .
  # test image
  - docker run ambianic/ambianic --version
  # push image
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      docker tag ambianic/ambianic ambianic/ambianic:$TAG
      docker push ambianic/ambianic:$TAG
      docker push ambianic/ambianic
    fi
  - docker images
  - cd $TRAVIS_BUILD_DIR
  - ./ambianic-test.sh
  - ./ambianic-docs.sh
  - echo $PWD
  - ls -al
  - ls -al tests/
after_success:
  - codecov # submit code coverage
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: docs/site
  on:
    branch: master
