language: python
sudo: required
services:
  - docker
before_install:
#  - python --version
# command to install dependencies
install:
  - cd build
  - ./ambianic-build.sh
  - pip3 install -U codecov
# command to run tests
script:
  # [x86]
  - docker images
  - cd $TRAVIS_BUILD_DIR
  - ./ambianic-test.sh
  - ./ambianic-docs.sh
  - echo $PWD
  - ls -al
  - ls -al tests/
  # [arm]
  # Raspberry PI section
  # prepare qemu
  - cd build
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # build image
  - sudo docker build -f Dev.Dockerfile -t ambianic/ambianic .
  # test image
  - docker run ambianic/ambianic --version
  # push image
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      TAG=dev-arm
      docker tag ambianic/ambianic ambianic/ambianic:$TAG
      docker push ambianic/ambianic:$TAG
      docker push ambianic/ambianic
    fi
after_success:
  - codecov # submit code coverage
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: docs/site
  on:
    branch: master
