language: python
sudo: required
services:
  - docker
before_install:
  - python --version
 # command to install dependencies
install:
  - ./ambianic-build.sh
  - pip3 install codecov
# command to run tests
script:
  - docker images
  - ./ambianic-test.sh
  - ./ambianic-docs.sh
  - pip3 install -U  --user codecov
after_success:
  - codecov # submit code coverage
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: docs/site
  on:
    branch: master
