language: python
python:
  - "3.7"
before_install:
  - sudo apt-get update
  - sudo apt install libgirepository1.0-dev
  - sudo apt-get install libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-pulseaudio
  - sudo apt-get install python-gst-1.0
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
  
