sudo: required
services:
  - docker
before_install:
#  - ./ambianic-build.sh
#  - python --version
#  - pip install -U pip
#  - pip install -U pytest # unit test tool
#  - pip install codecov # code coverage tool
#  - pip install pytest-cov # coverage plugin for pytest
#  - pip install pylint # python linter
 # command to install dependencies
install:
  - ./ambianic-build.sh
#  - pip install -r requirements.txt
# command to run tests
script:
  - docker images
  - ./ambianic-test.sh
#  - pytest --cov-report=xml --cov=ambianic
#  - pylint --errors-only ambianic
#after_success:
#  - codecov # submit code coverage
