language: python
python:
  - "3.7"
before_install:
  - sudo apt-get update
  - sudo apt install libgirepository1.0-dev
  - sudo apt-get install python-gst-1.0 \
      gir1.2-gstreamer-1.0 gir1.2-gst-plugins-base-1.0 \
      gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly \
      gstreamer1.0-tools  
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
  
