# Ambianic base config
dynaconf_merge: true
default:
  data_dir: ./data

  logging:
    file: ./data/ambianic-log.txt
    level: INFO

  timeline:
    event_log: ./data/timeline-event-log.yaml

  notifications:
    providers: {}
    template:
      title: "[Ambianic.ai] {event} recognized"
      body: >
        {event} event has been recognized by the system.
        Visit https://ui.ambianic.ai/ for more details.
    labels:
      fall_detection: Fall
      object_detection: Object

  sources: {}

  ai_models:
    image_detection:
      model:
        tflite: ai_models/mobilenet_ssd_v2_coco_quant_postprocess.tflite
        edgetpu: ai_models/mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite
      labels: ai_models/coco_labels.txt
    face_detection:
      model:
        tflite: ai_models/mobilenet_ssd_v2_face_quant_postprocess.tflite
        edgetpu: ai_models/mobilenet_ssd_v2_face_quant_postprocess_edgetpu.tflite
      labels: ai_models/coco_labels.txt
      top_k: 2

  pipelines: {}
