######################################
#  Ambianic main configuration file  #
######################################
version: '1.3.29'

# path to the data directory
data_dir: ./data

# Set logging level to one of DEBUG, INFO, WARNING, ERROR
logging:
  file: ./data/ambianic-log.txt
  level: INFO

# Pipeline event timeline configuration
timeline:
  event_log: ./data/timeline-event-log.yaml

# Cameras and other input data sources
# Using Home Assistant conventions to ease upcoming integration
sources:
  src_entry_area_cam:
    uri: rtsp://192.168.7.13:554/11
    # type: video, audio, or auto
    type: video
    live: true

ai_models:
  image_detection:
    model:
      tflite: ai_models/mobilenet_ssd_v2_coco_quant_postprocess.tflite
      edgetpu: ai_models/mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite
    labels: ai_models/coco_labels.txt
  face_detection:
    model:
      tflite: ai_models/mobilenet_ssd_v2_face_quant_postprocess.tflite
      edgetpu: ai_models/mobilenet_ssd_v2_face_quant_postprocess_edgetpu.tflite
    labels: ai_models/coco_labels.txt
    top_k: 2

# A named pipeline defines an ordered sequence of operations
# such as reading from a data source, AI model inference, saving samples and others.
pipelines:

  # sequence of piped operations for use in daytime front door watch
  entry_area_watch:
    - source:
        id: src_entry_area_cam
    - detect_objects: # run ai inference on the input data
        <<:
          id: image_detection
        confidence_threshold: 0.8
    - save_detections: # save samples from the inference results
        positive_interval: 5 # how often (in seconds) to save samples with ANY results above the confidence thresho$
        idle_interval: 21600 # how often (in seconds) to save samples with NO results above the confidence threshold
    - detect_faces: # run ai inference on the samples from the previous element output
        <<:
          id: face_detection
        confidence_threshold: 0.8
    - save_detections: # save samples from the inference results
        positive_interval: 2
        idle_interval: 6000
