# Ambianic base config

data_dir: ./data

logging:
  file: ./data/ambianic-log.txt
  level: INFO

timeline:
  event_log: ./data/timeline-event-log.yaml

sources: {}

ai_models:
  image_detection:
    model:
      tflite: ai_models/mobilenet_ssd_v2_coco_quant_postprocess.tflite
      edgetpu: ai_models/mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite
    labels: ai_models/coco_labels.txt
  face_detection:
    model:
      tflite: ai_models/mobilenet_ssd_v2_face_quant_postprocess.tflite
      edgetpu: ai_models/mobilenet_ssd_v2_face_quant_postprocess_edgetpu.tflite
    labels: ai_models/coco_labels.txt
    top_k: 2

pipelines: {}
