#################################################
# Ambianic main configuration file              #
# ! Do not commit this file to git !            #
#                                               #
# Values in this file will override values from #
# config.defaults.yaml                          #
#                                               #
# You can also use config.local.yaml            #
# as a less ambiguous name for a  local version #
# of your ambianic-edge instance configuration  #
#################################################
