---
AI_MODELS:
  face_detection:
    labels: /opt/ambianic-edge/ai_models/coco_labels.txt
    model:
      edgetpu: /opt/ambianic-edge/ai_models/mobilenet_ssd_v2_face_quant_postprocess_edgetpu.tflite
      tflite: /opt/ambianic-edge/ai_models/mobilenet_ssd_v2_face_quant_postprocess.tflite
    top_k: 2
  fall_detection:
    labels: /opt/ambianic-edge/ai_models/pose_labels.txt
    model:
      edgetpu: /opt/ambianic-edge/ai_models/posenet_mobilenet_v1_075_721_1281_quant_decoder_edgetpu.tflite
      tflite: /opt/ambianic-edge/ai_models/posenet_mobilenet_v1_100_257x257_multi_kpt_stripped.tflite
  image_detection:
    labels: /opt/ambianic-edge/ai_models/coco_labels.txt
    model:
      edgetpu: /opt/ambianic-edge/ai_models/mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite
      tflite: /opt/ambianic-edge/ai_models/mobilenet_ssd_v2_coco_quant_postprocess.tflite
DATA_DIR: ./data
DEFAULT:
  ai_models:
    face_detection:
      labels: /opt/ambianic-edge/ai_models/coco_labels.txt
      model:
        edgetpu: /opt/ambianic-edge/ai_models/mobilenet_ssd_v2_face_quant_postprocess_edgetpu.tflite
        tflite: /opt/ambianic-edge/ai_models/mobilenet_ssd_v2_face_quant_postprocess.tflite
      top_k: 2
    fall_detection:
      labels: /opt/ambianic-edge/ai_models/pose_labels.txt
      model:
        edgetpu: /opt/ambianic-edge/ai_models/posenet_mobilenet_v1_075_721_1281_quant_decoder_edgetpu.tflite
        tflite: /opt/ambianic-edge/ai_models/posenet_mobilenet_v1_100_257x257_multi_kpt_stripped.tflite
    image_detection:
      labels: /opt/ambianic-edge/ai_models/coco_labels.txt
      model:
        edgetpu: /opt/ambianic-edge/ai_models/mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite
        tflite: /opt/ambianic-edge/ai_models/mobilenet_ssd_v2_coco_quant_postprocess.tflite
  data_dir: ./data
  logging:
    file: ./data/ambianic-log.txt
    level: INFO
  notifications:
    providers: {}
    template:
      body: "${event} event has been recognized by the system. Visit ${event_details_url}\
        \ for more details.\n"
      title: '[Ambianic.ai] ${event} recognized'
  pipelines: {}
  sources: {}
  timeline:
    event_log: ./data/timeline-event-log.yaml
DISPLAY_NAME: Kitchen Device
FILE_TO_SAVE: /workspace/ambianic-edge/config.yaml
LOGGING:
  file: ./data/ambianic-log.txt
  level: INFO
MERGE: true
PIPELINES:
  area_watch:
  - source: picamera
  - detect_objects:
      ai_model: image_detection
      confidence_threshold: 0.6
      label_filter:
      - person
      - car
  - save_detections:
      idle_interval: 6000
      positive_interval: 300
  - detect_falls:
      ai_model: fall_detection
      confidence_threshold: 0.6
  - save_detections:
      idle_interval: 600000
      positive_interval: 10
SOURCES:
  picamera:
    live: true
    type: video
    uri: picamera
  recorded_cam_feed:
    uri: file:///workspace/tests/pipeline/avsource/test2-cam-person1.mkv
  webcam:
    live: true
    type: video
    uri: /dev/video0
TIMELINE:
  event_log: ./data/timeline-event-log.yaml
VERSION: 2020.12.11
