site_name: Ambianic Documentation
repo_url: https://github.com/ambianic/ambianic-core
nav:
    - Home: index.md
    - Python API: ambianic-python-api.md
    - Contributing: CONTRIBUTING.md
theme: mkdocs
