name: Build Docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3
    - name: Run doc build script
      run: |
        ${GITHUB_WORKSPACE}/build/ci-docs-job.sh
    - name: Deploy to github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/dist
