name: Ambianic Edge CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_x86:
    runs-on: ubuntu-latest
    env: 
      ARCH: "linux/amd64"
      TAG_SUFFIX: "amd64"
  build_arm:
    runs-on: ubuntu-latest
    env:
      ARCH: "linux/arm/v7"
      TAG_SUFFIX: "arm32v7"
  release:
    needs: [build_x86, build_arm]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Install npm
      run: |
        npm version
        npm ci
      env:
        CI: true
    - name: Semantic Release
      run: npx semantic-release
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
